SELECT * FROM supers_store.`sample - superstore`;

SELECT *FROM `sample - superstore`
LIMIT 5;

SELECT
COUNT(*)-COUNT(`ORDER ID`)AS MISSING_ORDERID,
COUNT(*)-COUNT(CATEGORY) AS MISSING_CATEGORY,
COUNT(*)-COUNT(PROFIT) AS MISSING_PROFIT,
COUNT(*)-COUNT(SALES)AS MISSING_PROFIT 
FROM `sample - superstore`;

SELECT `ROW ID`, COUNT(*)
FROM `sample - superstore`
GROUP BY `ROW ID`
HAVING COUNT(*)>1;

SELECT
	CATEGORY,
    ROUND(SUM(SALES),2) AS TOTAL_SALES,
    ROUND(SUM(PROFIT),2) AS TOTAL_PROFIT,
    ROUND((SUM(PROFIT)/SUM(SALES))*100,2) AS PROFIT_MARGIN
    FROM `sample - superstore`
    GROUP BY CATEGORY;
    
SELECT 
     `SUB-CATEGORY`,
     ROUND(SUM(SALES),2) AS TOTAL_SALES,
     ROUND(SUM(PROFIT),2)AS TOTAL_PROFIT,
     ROUND((SUM(PROFIT)/SUM(SALES))*100,2) AS PROFIT_MARGIN
     FROM `sample - superstore`
     GROUP BY `SUB-CATEGORY`
     ORDER BY PROFIT_MARGIN DESC;
     
     SELECT 
		REGION,
        ROUND(SUM(SALES),2) AS TOTAL_SALES,
        ROUND(SUM(PROFIT),2) AS TOTAL_PROFIT
	FROM `sample - superstore`
    GROUP BY REGION
    ORDER BY TOTAL_PROFIT DESC;
    
    SELECT
         `PRODUCT NAME`,
         ROUND(SUM(PROFIT),2) AS TOTAL_PROFIT
	FROM `sample - superstore`
    GROUP BY `PRODUCT NAME`
    ORDER BY TOTAL_PROFIT DESC
    LIMIT 10;
    
     SELECT
         `PRODUCT NAME`,
         ROUND(SUM(PROFIT),2) AS TOTAL_PROFIT
	FROM `sample - superstore`
    GROUP BY `PRODUCT NAME`
    ORDER BY TOTAL_PROFIT ASC
    LIMIT 10;
    
    SELECT 
        `PRODUCT NAME`,
        SUM(QUANTITY) AS QUANTITY_SOLD
	FROM `sample - superstore`
    GROUP BY `PRODUCT NAME`
    ORDER BY QUANTITY_SOLD DESC
    LIMIT 10;
    
    SELECT 
        `PRODUCT NAME`,
        SUM(QUANTITY) AS QUANTITY_SOLD
	FROM `sample - superstore`
    GROUP BY `PRODUCT NAME`
    ORDER BY QUANTITY_SOLD ASC
    LIMIT 10;
    
    
